version: '3.8'
services:
  postgresql:
    image: postgres:16.1
    container_name: transform_fhir_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local

